[General]
dns-server = tls://2001:4860:4860::8888:853,tls://2001:4860:4860::8844:853,tls://8.8.8.8:853,tls://8.8.4.4:853,https://dns.google/dns-query,2001:4860:4860::8888,2001:4860:4860::8844,8.8.8.8,8.8.4.4
fallback-dns-server = tls://77.88.8.88:853,https://safe.dot.dns.yandex.net/dns-query,2a02:6b8::feed:bad,77.88.8.88,system
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
dns-direct-fallback-proxy = true
private-ip-answer = false
routing-domain-resolve = true
bypass-system = false
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.0/8, localhost, *.local

[Rule]
FINAL,PROXY