[General]
dns-server = system, https://1.1.1.1/dns-query, https://8.8.8.8/dns-query
fallback-dns-server = https://1.0.0.1/dns-query, https://8.8.4.4/dns-query
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
dns-direct-fallback-proxy = true
private-ip-answer = false
routing-domain-resolve = true
bypass-system = false
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.0/8, localhost, *.local

[Rule]
FINAL,PROXY