[General]
dns-server = tls://9.9.9.9:853
fallback-dns-server = tls://9.9.9.9:853
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
dns-direct-fallback-proxy = true
private-ip-answer = false
routing-domain-resolve = true
bypass-system = false
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.0/8, localhost, *.local

[Rule]
FINAL,PROXY